language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '7'
  - '6'
  - '4'

script:
  - npm run lint
  - npm run test:headless
  - npm run coveralls

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
