language: node_js

notifications:
  email: false

node_js:
  - '7'
  - '6'
  - '4'

before_script:
  - npm prune

script:
  - npm run lint
  - npm run test:headless
  - npm run coveralls
  - npm run build

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
